### ISSUE TITLE
complete First version mockup of UI

### ISSUE THREAD

**Issue by cmodrono** [cburrows1/AlgoRythm#3]

**Comment by Laurence-RM** [comment]
### First version of settings UI mockup complete:
![SettingsUIMockup](https://user-images.githubusercontent.com/3759631/122429069-64e38180-cf8a-11eb-9059-10805d6d1175.png)


**GUI Features:**
- Profile Selection
- Style Selection
- Color Selection
- Visualizer Properties
- Preview of Visualizer
- Music Integration Options
- Audio Source Selection

Color scheme is temporary, waiting for team suggestions/agreement.
Might need to add more options for Spotify integration
